### ISSUE TITLE
[anomalie] Les messages se raffraîchissent sur tous les clients lorsqu'un nouvel utilisateur se connecte

### ISSUE THREAD

**Issue by Dev2ZooF** [Gynidark/Moosta#1]
Hello,

J'ai fait le test suivant :

1) Un utilisateur se connecte, prend un pseudo et tape quelques messages dans le chat
2) Un autre utilisateur se connecte et prend également un pseudo
3) Lorsque le deuxième utilisateur clique sur le bouton pour valider son pseudo, tous les messages affichés à l'écran du premier utilisateur sont supprimés

En regardant ton code, je pense que le problème est côté client, au moment ou tu catch l'event de socket "newUser" dans ton fichier chat.js à la ligne suivante :
$('#messages').html('')

Je suppose que tu avais mis ce morceau de code pour que le message "<pseudo> vient de se connecter" ne soit pas visible sur l'écran de l'utilisateur qui vient de se connecter, mais l'event est catché par tous les clients, ce qui explique que les messages s'effacent chez tout le monde.

Sinon très bon chat, réactif et plaisant en terme de design, merci pour ça :+1: :)

(PS : quand les gens se connecte ou se déconnecte, tu écris "viens de se (dé)connecter" plutôt que "vient de se (dé)connecter" ^^)

**Comment by Gynidark** [comment]
Bonjour Dev2',

Effectivement, j'ai moi même vu le souci et je compte bientôt le corriger; pour faire un peu de spoil, je compte mettre un système d'historique donc bien entendu le .html('') va partir et sera mieux organiser pour les personnes qui se connecte.

À propos de la faute merci beaucoup, je dois admettr que c'est pas mon fort. 😄 

En tout cas, merci pour la contribution ça fait plaisir d'avoir ce genre d'issue ça permet d'améliorer aussi le projet afin d'acquérir un projet clean. 👍 

Gynidark,
[http://gynidark.github.io](http://gynidark.github.io)

**Comment by Dev2ZooF** [comment]
Je t'en prie, tu peux m'appeler ZooF ou, à défaut, Aurélien ;)
Je suis impatient de voir ce que ça va donner !

**Comment by Gynidark** [comment]
Après quelques heures de réflexions, j'ai pu réalisé du code plus propre toute en apportant les corrections sur ce que tu m'avais signalé dans l'issue.

Les modifications apportés :
- Ajout des commentaires(JSDoc).
- Ajout d'une fonction ‘createElement‘ qui gère des templates.
- Suppression du .html() qui réalisé un petit problème.
- Ajout de la fonction ‘actionsSocket‘ pour réunir toute mes actions.

Merci encore pour la contribution ! 😊
