### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by hexicans** [Gynidark/Moosta#2]
Hello,

I have this error : 

> root@redondance:/home/sites/tchatnodejs/Moosta# node app.js
> /home/sites/tchatnodejs/Moosta/app.js:17
>     let me
>     ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:990:3

`

**Comment by Gynidark** [comment]
Hello,

Your version of nodejs ?

**PS** : Your version of nodejs must be greater than or equal to 7.4

*this is my fault, I have not put a minimum version in the `package.json` file.* 😅 

Cordially,

**Comment by hexicans** [comment]
hello,

ah ok.. i'am on v4.6.2 :(

**Comment by Gynidark** [comment]
Hi, 

That's what blocks :confused:
